const fs = require('fs');
const path = require('path');

const catalogDir = path.join(__dirname, '../public/catalog');
const outputFile = path.join(__dirname, '../lib/generated-data.ts');

const dirs = fs.readdirSync(catalogDir, { withFileTypes: true })
  .filter(dirent => dirent.isDirectory())
  .map(dirent => dirent.name)
  .sort((a, b) => {
    // Basic natural sort for RC-001, RC-002, etc.
    return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
  });

const items = [];

for (const dir of dirs) {
  const dirPath = path.join(catalogDir, dir);
  const dataPath = path.join(dirPath, 'data.json');

  if (fs.existsSync(dataPath)) {
    try {
      const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

      // Dynamically detect cover image extension
      let coverExt = '.jpg';
      if (fs.existsSync(path.join(dirPath, 'cover.png'))) {
        coverExt = '.png';
      } else if (fs.existsSync(path.join(dirPath, 'cover.jpeg'))) {
        coverExt = '.jpeg';
      } else if (fs.existsSync(path.join(dirPath, 'cover.webp'))) {
        coverExt = '.webp';
      }

      const item = {
        id: data.id,
        slug: data.collectionNumber ? data.collectionNumber.trim() : '',
        collectionNumber: data.collectionNumber ? data.collectionNumber.trim() : '',
        title: data.title ? data.title.trim() : '',
        price: data.price,
        category: data.category ? data.category.trim() : '',
        condition: data.condition ? data.condition.trim() : '',
        badge: data.badge ? data.badge.trim() : null,
        status: data.status ? data.status.trim() : '',
        image: `/catalog/${dir}/cover${coverExt}`,
        description: data.description ? data.description.trim() : '',
      };

      items.push(item);
    } catch (err) {
      console.error(`Error processing ${dir}:`, err);
    }
  }
}

// Generate TS file content
const tsContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// This file is generated by scripts/sync-data.js
import { CollectibleItem } from './data';

export const collectibles: CollectibleItem[] = ${JSON.stringify(items, null, 2)};
`;

fs.writeFileSync(outputFile, tsContent, 'utf-8');
console.log(`✅ Automatically synchronized ${items.length} items from public/catalog to lib/generated-data.ts`);
