const fs = require('fs');
const path = require('path');

const catalogDir = path.join(__dirname, '../public/catalog');
const soldFile = path.join(__dirname, '../public/sold.json');
const outputFile = path.join(__dirname, '../lib/generated-data.ts');

// =============================================
// 1. Load & Normalize Sold List from public/sold.json
// =============================================
function loadSoldList() {
  if (!fs.existsSync(soldFile)) {
    console.log('ℹ️  No sold.json found — skipping sold status override.');
    return new Set();
  }

  try {
    const raw = JSON.parse(fs.readFileSync(soldFile, 'utf-8'));
    if (!Array.isArray(raw)) {
      console.warn('⚠️  sold.json is not an array — skipping.');
      return new Set();
    }

    const normalized = raw.map(normalizeCollectionNumber).filter(Boolean);
    console.log(`📋 Loaded ${normalized.length} sold item(s) from sold.json: ${normalized.join(', ')}`);
    return new Set(normalized);
  } catch (err) {
    console.error('❌ Error reading sold.json:', err.message);
    return new Set();
  }
}

/**
 * Normalize any user input into "RC-XXX" format.
 * Examples:
 *   "rc 12"    → "RC-012"
 *   "rc-012"   → "RC-012"
 *   "RC-12"    → "RC-012"
 *   "rc012"    → "RC-012"
 *   "RC-001"   → "RC-001"
 *   "12"       → "RC-012"
 */
function normalizeCollectionNumber(input) {
  if (typeof input !== 'string') return null;

  // Strip whitespace, uppercase
  let s = input.trim().toUpperCase();

  // Remove "RC" prefix and any separator (dash, space, nothing)
  s = s.replace(/^RC[\s\-]?/, '');

  // What remains should be numeric
  const num = parseInt(s, 10);
  if (isNaN(num)) {
    console.warn(`⚠️  Could not normalize "${input}" — skipping.`);
    return null;
  }

  return `RC-${String(num).padStart(3, '0')}`;
}

// =============================================
// 2. Scan catalog directories
// =============================================
const soldSet = loadSoldList();

const dirs = fs.readdirSync(catalogDir, { withFileTypes: true })
  .filter(dirent => dirent.isDirectory())
  .map(dirent => dirent.name)
  .sort((a, b) => {
    // Basic natural sort for RC-001, RC-002, etc.
    return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
  });

const items = [];

for (const dir of dirs) {
  const dirPath = path.join(catalogDir, dir);
  const dataPath = path.join(dirPath, 'data.json');

  if (fs.existsSync(dataPath)) {
    try {
      const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

      // Dynamically detect cover image extension
      let coverExt = '.jpg';
      if (fs.existsSync(path.join(dirPath, 'cover.png'))) {
        coverExt = '.png';
      } else if (fs.existsSync(path.join(dirPath, 'cover.jpeg'))) {
        coverExt = '.jpeg';
      } else if (fs.existsSync(path.join(dirPath, 'cover.webp'))) {
        coverExt = '.webp';
      }

      const collectionNumber = data.collectionNumber ? data.collectionNumber.trim() : '';

      // Determine status: override to "Sold" if in sold list
      let status = data.status ? data.status.trim() : '';
      if (soldSet.has(collectionNumber)) {
        status = 'Sold';
      }

      const item = {
        id: data.id,
        slug: collectionNumber,
        collectionNumber: collectionNumber,
        title: data.title ? data.title.trim() : '',
        price: data.price,
        category: data.category ? data.category.trim() : '',
        condition: data.condition ? data.condition.trim() : '',
        badge: data.badge ? data.badge.trim() : null,
        status: status,
        image: `/catalog/${dir}/cover${coverExt}`,
        description: data.description ? data.description.trim() : '',
      };

      items.push(item);
    } catch (err) {
      console.error(`Error processing ${dir}:`, err);
    }
  }
}

// =============================================
// 3. Generate TS file
// =============================================
const soldCount = items.filter(i => i.status === 'Sold').length;

const tsContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// This file is generated by scripts/sync-data.js
import { CollectibleItem } from './data';

export const collectibles: CollectibleItem[] = ${JSON.stringify(items, null, 2)};
`;

fs.writeFileSync(outputFile, tsContent, 'utf-8');
console.log(`✅ Automatically synchronized ${items.length} items from public/catalog to lib/generated-data.ts`);
if (soldCount > 0) {
  console.log(`🔴 ${soldCount} item(s) marked as SOLD from sold.json`);
}
